version: "3.7"

services:
  server:
    build: .
    environment:
      - NODE_ENV=production
      - UPLOAD_DIRECTORY=${UPLOAD_DIRECTORY}
      - UPLOAD_BASE_URL=${UPLOAD_BASE_URL}
      - PORT=4000
